=== veki24/Laboratorijska_vje-ba_OR/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://example.com/klub-igrac-schema.json",
    "title": "Podaci o klubovima i igračima",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "klub_id": {
                "type": "integer",
                "description": "Jedinstveni identifikator kluba"
            },
            "ime_kluba": {
                "type": "string",
                "description": "Ime kluba"
            },
            "grad": {
                "type": "string",
                "description": "Grad gdje se klub nalazi"
            },
            "osnovan": {
                "type": "integer",
                "description": "Godina osnivanja kluba"
            },
            "stadion": {
                "type": "string",
                "description": "Naziv stadiona kluba"
            },
            "kapacitet_stadiona": {
                "type": "integer",
                "description": "Kapacitet stadiona"
            },
            "liga": {
                "type": "string",
                "description": "Liga u kojoj klub igra"
            },
            "drzava": {
                "type": "string",
                "description": "Država kluba"
            },
            "broj_osvojenih_titula": {
                "type": "integer",
                "description": "Broj osvojenih titula kluba"
            },
            "trener": {
                "type": "string",
                "description": "Trener kluba"
            },
            "igrac_id": {
                "type": "integer",
                "description": "Jedinstveni identifikator igrača"
            },
            "ime_igraca": {
                "type": "string",
                "description": "Ime igrača"
            },
            "pozicija": {
                "type": "string",
                "description": "Pozicija igrača"
            },
            "broj_dresa": {
                "type": "integer",
                "description": "Broj dresa igrača"
            },
            "godine": {
                "type": "integer",
                "description": "Godine igrača"
            },
            "nacionalnost": {
                "type": "string",
                "description": "Nacionalnost igrača"
            },
            "broj_golova": {
                "type": "integer",
                "description": "Broj postignutih golova igrača"
            },
            "broj_asistencija": {
                "type": "integer",
                "description": "Broj asistencija igrača"
            },
            "godine_u_klubu": {
                "type": "integer",
                "description": "Broj godina koje je igrač proveo u klubu"
            }
        },
        "required": [
            "klub_id",
            "ime_kluba",
            "grad",
            "osnovan",
            "stadion",
            "kapacitet_stadiona",
            "liga",
            "drzava",
            "broj_osvojenih_titula",
            "trener",
            "igrac_id",
            "ime_igraca",
            "pozicija",
            "broj_dresa",
            "godine",
            "nacionalnost",
            "broj_golova",
            "broj_asistencija",
            "godine_u_klubu"
        ]
    }
}

=== veki24/Laboratorijska_vje-ba_OR/public/data/klub.json
[
    {
      "klub_id": 7,
      "ime_kluba": "NK Jarun",
      "grad": "Zagreb",
      "osnovan": 1921,
      "stadion": "Stadion NK Jarun",
      "kapacitet_stadiona": 1500,
      "liga": "Supersport Prva NL",
      "drzava": "Hrvatska",
      "broj_osvojenih_titula": 0,
      "trener": "Jerko Leko",
      "igrac_id": 1,
      "ime_igraca": "Karlo Abramović",
      "pozicija": "Napadač",
      "broj_dresa": 17,
      "godine": 24,
      "nacionalnost": "Hrvatska",
      "broj_golova": 11,
      "broj_asistencija": 0,
      "godine_u_klubu": 3
    },
    {
      "klub_id": 9,
      "ime_kluba": "HNK Cibalia",
      "grad": "Vinkovci",
      "osnovan": 1919,
      "stadion": "Stadion HNK Cibalia",
      "kapacitet_stadiona": 10500,
      "liga": "Supersport Prva NL",
      "drzava": "Hrvatska",
      "broj_osvojenih_titula": 1,
      "trener": "Ivvan Karaula",
      "igrac_id": 2,
      "ime_igraca": "Jurica Bajić",
      "pozicija": "Napadač",
      "broj_dresa": 13,
      "godine": 24,
      "nacionalnost": "Hrvatska",
      "broj_golova": 9,
      "broj_asistencija": 2,
      "godine_u_klubu": 4
    },
    {
      "klub_id": 1,
      "ime_kluba": "HNK Vukovar 1991",
      "grad": "Vukovar",
      "osnovan": 1991,
      "stadion": "Stadion Borovo",
      "kapacitet_stadiona": 6000,
      "liga": "Supersport Prva NL",
      "drzava": "Hrvatska",
      "broj_osvojenih_titula": 0,
      "trener": "Branko Karačić",
      "igrac_id": 3,
      "ime_igraca": "Mateo Andacic",
      "pozicija": "Napadač",
      "broj_dresa": 15,
      "godine": 26,
      "nacionalnost": "Njemačka",
      "broj_golova": 4,
      "broj_asistencija": 0,
      "godine_u_klubu": 3
    },
    {
      "klub_id": 5,
      "ime_kluba": "NK Sesvete",
      "grad": "Sesvete",
      "osnovan": 1945,
      "stadion": "Stadion Sv. Josip Radnik",
      "kapacitet_stadiona": 3000,
      "liga": "Supersport Prva NL",
      "drzava": "Hrvatska",
      "broj_osvojenih_titula": 1,
      "trener": "Mario Rac",
      "igrac_id": 4,
      "ime_igraca": "Ivor Ljubanović",
      "pozicija": "Napadač",
      "broj_dresa": 9,
      "godine": 25,
      "nacionalnost": "Hrvatska",
      "broj_golova": 12,
      "broj_asistencija": 3,
      "godine_u_klubu": 2
    },
    {
      "klub_id": 3,
      "ime_kluba": "NK Dubrava Tim Kabel",
      "grad": "Zagreb",
      "osnovan": 1948,
      "stadion": "Stadion ŠRC Grana-Klaka",
      "kapacitet_stadiona": 2000,
      "liga": "Supersport Prva NL",
      "drzava": "Hrvatska",
      "broj_osvojenih_titula": 0,
      "trener": "Davor Mladina",
      "igrac_id": 5,
      "ime_igraca": "Tin Sarkaj",
      "pozicija": "Golman",
      "broj_dresa": 1,
      "godine": 22,
      "nacionalnost": "Hrvatska",
      "broj_golova": 0,
      "broj_asistencija": 0,
      "godine_u_klubu": 3
    },
    {
      "klub_id": 2,
      "ime_kluba": "NK Opatija",
      "grad": "Opatija",
      "osnovan": 1908,
      "stadion": "Stadion Kantrida",
      "kapacitet_stadiona": 10600,
      "liga": "Supersport Prva NL",
      "drzava": "Hrvatska",
      "broj_osvojenih_titula": 0,
      "trener": "Zoran Bogolin",
      "igrac_id": 6,
      "ime_igraca": "Luka Marić",
      "pozicija": "Obrambeni",
      "broj_dresa": 21,
      "godine": 37,
      "nacionalnost": "Hrvatska",
      "broj_golova": 5,
      "broj_asistencija": 1,
      "godine_u_klubu": 1
    },
    {
      "klub_id": 4,
      "ime_kluba": "NK Croatia Zmijavci",
      "grad": "Zmijavci",
      "osnovan": 1974,
      "stadion": "Stadion ŠRC Marijan šuto Mrma",
      "kapacitet_stadiona": 1500,
      "liga": "Supersport Prva NL",
      "drzava": "Hrvatska",
      "broj_osvojenih_titula": 0,
      "trener": "Marko Kartelo",
      "igrac_id": 7,
      "ime_igraca": "Tomislav Arković",
      "pozicija": "Obrambeni",
      "broj_dresa": 4,
      "godine": 19,
      "nacionalnost": "Hrvatska",
      "broj_golova": 0,
      "broj_asistencija": 0,
      "godine_u_klubu": 1
    },
    {
      "klub_id": 6,
      "ime_kluba": "NK Rudeš",
      "grad": "Zagreb",
      "osnovan": 1957,
      "stadion": "Stadion Rudeš",
      "kapacitet_stadiona": 2500,
      "liga": "Supersport Prva NL",
      "drzava": "Hrvatska",
      "broj_osvojenih_titula": 2,
      "trener": "Samir Toplak",
      "igrac_id": 8,
      "ime_igraca": "Petar Cuic",
      "pozicija": "Vezni",
      "broj_dresa": 21,
      "godine": 25,
      "nacionalnost": "Hrvatska",
      "broj_golova": 5,
      "broj_asistencija": 6,
      "godine_u_klubu": 1
    },
    {
      "klub_id": 8,
      "ime_kluba": "HNK Orijent",
      "grad": "Rijeka",
      "osnovan": 1919,
      "stadion": "Stadion Krimeja",
      "kapacitet_stadiona": 3000,
      "liga": "Supersport Prva NL",
      "drzava": "Hrvatska",
      "broj_osvojenih_titula": 0,
      "trener": "Alen Šušnić",
      "igrac_id": 9,
      "ime_igraca": "Mateo Monjac",
      "pozicija": "Vezni",
      "broj_dresa": 17,
      "godine": 28,
      "nacionalnost": "Hrvatska",
      "broj_golova": 33,
      "broj_asistencija": 8,
      "godine_u_klubu": 6
    },
    {
      "klub_id": 10,
      "ime_kluba": "NK Dugopolje",
      "grad": "Dugopolje",
      "osnovan": 1952,
      "stadion": "Stadion Hrvatski vitezovi",
      "kapacitet_stadiona": 5000,
      "liga": "Supersport Prva NL",
      "drzava": "Hrvatska",
      "broj_osvojenih_titula": 1,
      "trener": "Mirko Labrović",
      "igrac_id": 10,
      "ime_igraca": "Dario Barada",
      "pozicija": "Obrambeni",
      "broj_dresa": 6,
      "godine": 25,
      "nacionalnost": "Hrvatska",
      "broj_golova": 4,
      "broj_asistencija": 4,
      "godine_u_klubu": 1
    },
    {
      "klub_id": 11,
      "ime_kluba": "NK BSK Bijelo Brdo",
      "grad": "Bijelo Brdo",
      "osnovan": 1935,
      "stadion": "Stadion BSK",
      "kapacitet_stadiona": 1500,
      "liga": "Supersport Prva NL",
      "drzava": "Hrvatska",
      "broj_osvojenih_titula": 0,
      "trener": "Igor Budiša",
      "igrac_id": 11,
      "ime_igraca": "Mustedanagic Zinedin",
      "pozicija": "Vezni",
      "broj_dresa": 11,
      "godine": 26,
      "nacionalnost": "Bosna i Hercegovina",
      "broj_golova": 55,
      "broj_asistencija": 7,
      "godine_u_klubu": 1
    },
    {
      "klub_id": 12,
      "ime_kluba": "NK Zrinski Osječko 1664",
      "grad": "Osijek",
      "osnovan": 1664,
      "stadion": "Stadion Gradski vrt",
      "kapacitet_stadiona": 18000,
      "liga": "Supersport Prva NL",
      "drzava": "Hrvatska",
      "broj_osvojenih_titula": 0,
      "trener": "Dražen Dikonić",
      "igrac_id": 12,
      "ime_igraca": "Gojko Gazde",
      "pozicija": "Vezni",
      "broj_dresa": 27,
      "godine": 24,
      "nacionalnost": "Hrvatska",
      "broj_golova": 6,
      "broj_asistencija": 0,
      "godine_u_klubu": 1
    }
  ]
